### ISSUE TITLE
censoring when simulating data

### ISSUE THREAD

**Issue by adibender** [adibender/pammtools#108]
One thing we (not necessarily @pkopper) should think about in the context of #106 is censoring. 

So far I always added censoring manually after the call to `sim_pexp`. The question is if that could be usefully integrated within `sim_pexp`, potentially as a special case of CR (where two linear predictors/event times are generated but independent of each other and the smaller one is selected) or if its better to add a function `add_censoring` that can be called after generating the survival times, e.g.

The former would require some way to specify if `rhs_censoring` is a competing risk or a censoring specification, for which I don't see an easy way to do...

```r 
data %>% sim_pexp(~rhs_event|rhs_censoring)
# or
data %>% sim_pexp(~rhs) %>% add_censoring(~rhs_censoring)
```

**Comment by pkopper** [comment]
Thank you for that note.
I tend to the first suggestion of your intuitively as this is as I would implement it in the non-PAMM set up, too.
However, I'll have a look at it and assign myself.

**Comment by adibender** [comment]
this will go into https://github.com/adibender/simpexp
