### ISSUE TITLE
CI types: documentation, evaluation

### ISSUE THREAD

**Issue by fabian-s** [adibender/pammtools#115]
do we have an evaluation of the various CI types anywhere?
if not, we should. 
could be part of a **vignette on inference**. 

also: needs more documentation in code, and in man pages

**Comment by adibender** [comment]
I had some simulations on that in the introduction to my thesis. I've started a HP collecting simulation results for PAMMs here: https://adibender.github.io/simpamm/index.html
Will try to update sometime this month to include all simulations we've done so far. 

Then, we can include links to the various simulaitons in the documentation.
