### ISSUE TITLE
Import plyr

### ISSUE THREAD

**Issue by thomasp85** [adibender/pammtools#141]
The new version of ggplot2 no longer depend on plyr. pammtools has somehow been able to have `plyr::` calls in its code without explicitly depending on plyr, but these will now break as plyr is no longer present on a clean system.

To fix this, add plyr to Imports in the DESCRIPTION file and submit to CRAN

**Comment by adibender** [comment]
> Dear maintainer,

> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_pammtools.html>.
> 
> Specifically, see the ERROR for check flavor r-patched-solaris-x86.
> 
> This can be reproduced by checking with --as-cran on any platform, which
> arranges to do all run time checks with a user library containing only
> packages at least suggested.
> 
> Can you please fix your package dependencies (or code) as necessary?
> 
> Please correct before 2020-03-26 to safely retain your package on CRAN.
> 
> Best,
> -k
