### ISSUE TITLE
data trafo for left-truncation

### ISSUE THREAD

**Issue by adibender** [adibender/pammtools#152]

**Comment by pcross-usgs** [comment]
Hi there,  I'd like to upvote this issue. I'm excited about this package as I usually do this sort of thing with a custom bayesian analysis. But, being lazy I thought I'd see what I could using pammtools, however almost every dataset I work with has some sort of interval censoring or left-censoring. 
Cheers, 

Paul Cross

**Comment by adibender** [comment]
Hi thanks, 
left truncation is possible (and easy), but left-/interval-censoring might not be possible (directly). Currently pammtools only supports models that only require data transformation, while for left-/interval-censoring it might be necessary to implement the likelihood

**Comment by pcross-usgs** [comment]
Thanks!

**Comment by adibender** [comment]
So left-**truncation** should be easy using `survSplit` with a `Surv(start, stop, status)~.` type formula. But we need to update `split_data` and `as_ped` to allow/work with formulas with 3 arguments.
