### ISSUE TITLE
direction argument to geom_stepribbon

### ISSUE THREAD

**Issue by eds-slim** [adibender/pammtools#154]
Hi,
thanks for the great package. Would it be possible to implement the `direction` argument in `geom_stepribbon` with possible values `hv`, `vh`, and `mid`, just like in `geom_step`?

**Comment by modche** [comment]
Yes, that would be great as `mid` is often much better than `hv` or `vh`.

**Comment by adibender** [comment]
Thanks, will look into it

**Comment by adibender** [comment]
@fabian-s any progress?

**Comment by modche** [comment]
+1 
Especially when `geom_stepribbon` is used to show the IQR range over time it would be nice to align the ribbons with `geom_step`. 

<img width="211" alt="image" src="https://user-images.githubusercontent.com/13642619/112468921-21052580-8d69-11eb-9f4d-589541553b05.png">

**Comment by fabian-s** [comment]
see https://github.com/adibender/pammtools/pull/193

**Comment by BrunoMioto** [comment]
+1!

**Comment by fabian-s** [comment]
https://github.com/adibender/pammtools/commit/38a75f7f57e49ae574e7e6cae383d33faebde4d9
```
huron <- data.frame(year = 1875:1885, level = as.vector(LakeHuron)[1:11])
h <- ggplot(huron, aes(year))

(h + geom_stepribbon(aes(ymin = level - 1, ymax = level + 1), fill = "grey70", direction = "vh") +
     geom_step(aes(y = level), direction = "vh") + ggtitle("vh")) /
(h + geom_stepribbon(aes(ymin = level - 1, ymax = level + 1), fill = "grey70", direction = "hv") +
  geom_step(aes(y = level), direction = "hv")  + ggtitle("hv")) /
(h + geom_stepribbon(aes(ymin = level - 1, ymax = level + 1), fill = "grey70", direction = "mid") +
  geom_step(aes(y = level), direction = "mid")  + ggtitle("mid"))
```
![image](https://user-images.githubusercontent.com/998541/157875911-08e5f89e-8486-4405-a54f-f6bbba9aa453.png)

**Comment by fabian-s** [comment]
@modche @eds-slim @brunomioto 

note that if you use a direction argument other than hv for the piecewise-constant hazard rates etc returned by pammtools, what you plot is no longer exactly the hazard rate. The only *correct* way to plot such right-continuous (cadlag) step functions is `hv`, since the "jump" is at the end of the interval not at the beginning or in the middle...

**Comment by modche** [comment]
I just use the geom, not the analysis functions of the package.
