### ISSUE TITLE
mgcv::bam() still having problems with offset terms when discrete=T

### ISSUE THREAD

**Issue by StephanZhechev** [adibender/pammtools#160]
Hello,

I am fitting GAM models on fairly large data sets (up to 600k observations) and I decided to use the recommended mgcv::bam() function. I have been experiencing problems with the ```discrete=T``` option if I fit models with an ```offset``` term, which is usually the case for me. I stumbled upon this issue 

https://github.com/adibender/pammtools/issues/117

It seems that the problem is still not solved.

Regards,
Stephan

**Comment by fabian-s** [comment]
Cannot reproduce #117 with R 4.0.2 and mgcv 1.8-31 - **does** seem to have been fixed for good.

In any case, this is not a `pammtools` issue, so get off our lawn! ;)

**Comment by StephanZhechev** [comment]
Hi,

Yes, I definitely don't get the problem with ```pammtools```. Sorry, that was the wrong place to complain :)
