### ISSUE TITLE
Anaconda package

### ISSUE THREAD

**Issue by RenzoTale88** [adibender/pammtools#199]
Hello,
I was wondering if it would be possible to release the package also as an anaconda package, so that it can be installed into local anaconda environments? I'm asking because that would simplify working and creating docker images, as well as workflows that can therefore access this package :)
Andrea

**Comment by adibender** [comment]
Hi, what would it take to release it as an anaconda package?

**Comment by adibender** [comment]
I don't think I can control that. At least I didn't find any info on how to add packages. Did you try any of the approaches here: https://stackoverflow.com/questions/36652015/how-to-install-r-packages-not-in-the-conda-repositories

**Comment by RenzoTale88** [comment]
@adibender I've managed to build the anaconda package. Do you want to get the recipe files to create it and upload it yourself, or do you prefer me to upload it directly?

**Comment by adibender** [comment]
Probably good, if you tell me how to do it (or link some documentation), so I can update the package when there is a new version.

**Comment by RenzoTale88** [comment]
Sure thing!
So, I've proceeded following the instruction in the link you sent, towards the bottom. You can find more here too:
https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-r-pkgs.html
Briefly, I've first created an anaconda skeleton:
```
mkdir ~/pammtools && cd ~/pammtools
conda skeleton cran pammtools
```
This will create all the files needed to build an anaconda package.
Then, I've modified the meta.yml in the folder just created to add the following lines:
```
    - conda-forge::r-base<4
    - conda-forge::r-cowplot
    - conda-forge::r-tidyverse
    - conda-forge::r-reshape2
    - conda-forge::r-ggfortify
    - conda-forge::r-lazyeval
    - conda-forge::r-plyr
```
Under the requirements > host section.
Then, I've built the package as follow:
```
cd ~
conda build pammtools
```
This will create the pammtools tar file in your anaconda installation path.
You have then to follow these instructions to upload to anaconda cloud and make it available as a package:
https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-r-pkgs.html#optional-uploading-packages-to-anaconda-org

Hope this help!

Andrea

**Comment by adibender** [comment]
Thanks, I will try when I have a little more time

**Comment by adibender** [comment]
Hi @RenzoTale88 I will be on vacation through august and won't have time for that beforehand. If you need it urgently, go ahead and upload yourself. I will then try to keep the conda upload up to date for new versions

**Comment by RenzoTale88** [comment]
Hi @adibender I'm not in a hurry, no worries. Enjoy your holiday!

**Comment by Nosferican** [comment]
Any update on this?

**Comment by adibender** [comment]
I tried, but something didn't work, so I didn't pursue it further.

**Comment by adibender** [comment]
I will close this, reopen if someone is willing to take this on.
