### ISSUE TITLE
method argument not inherited

### ISSUE THREAD

**Issue by StaffanBetner** [adibender/pammtools#200]
Even if I specify `method = "REML"` in `pamm`, it still uses UBRE. See reprex:

``` r
library(survival)
library(pammtools)
#> 
#> Attaching package: 'pammtools'
#> The following object is masked from 'package:stats':
#> 
#>     filter

as_ped(Surv(time, status) ~ temperature + voltage, data = capacitor) |>
  pamm(formula = ped_status ~ s(tend)+temperature+voltage, method="REML")
#> 
#> Family: poisson 
#> Link function: log 
#> 
#> Formula:
#> ped_status ~ s(tend) + temperature + voltage
#> 
#> Estimated degrees of freedom:
#> 8.29  total = 11.29 
#> 
#> UBRE score: -0.7208745
```

It seems like nothing is done with `method = "REML"` when looking in the code for `pamm`, so an alternative might just be to remove it from the arguments so that it will be correctly handled via the dots.

**Comment by adibender** [comment]
@StaffanBetner you are right, thanks for reporting! Would you like to contribute a PR?

**Comment by StaffanBetner** [comment]
I will look into it! I had a brief look at the source code, and the fix is (probably) extremely simple.

**Comment by adibender** [comment]
perfect, thx!
