### ISSUE TITLE
Odds ratio or Hazard ratio for PAMMs?

### ISSUE THREAD

**Issue by ningyile** [adibender/pammtools#229]
Recently I had a question about the statistical measure of the PAMMs. I used the `tbl_regression` function in the `gtsummary` package for the results of the PAMMs, and I found that the result was `OR`, but I remembered that in the tutorial of [`Time-varying effects`](https://adibender.github.io/pammtools/articles/tveffects.html) that the Y-axis was the log hazard. In addition, the PAMMs model has the `add_hazard` function. The statistical measure of the GAM model is `OR`. I'm confused about whether the result of the PAMMs model is OR or HR. @adibender

**Comment by adibender** [comment]
Hello, in general, PAMMs model the hazard. exp(beta) gives you hazard ratio. 
`add_hazard` calculates the hazard, given the specified covariates and time, unless you specify the `reference` argument, which then gives you the hazard ratio compared to subjects specified in the data set, compared to subject specified in `reference` argument. 
Hope this helps.

**Comment by adibender** [comment]
@ningyile Is your question answered?

**Comment by ningyile** [comment]
> @ningyile Is your question answered?

Thank you very much! Your answer helps me a lot!
