### ISSUE TITLE
Wrong comparison of intervals  in `warn_about_new_time_points.pamm`?

### ISSUE THREAD

**Issue by gavinsimpson** [adibender/pammtools#235]
I think there's a little buglet in the code to compare intervals used in a PAMM and in `newdata` supplied for prediction. In `warn_about_new_time_points.pamm` we have:

https://github.com/adibender/pammtools/blob/ab4caeae41748c395772615c70a0cd5e206ebfe6/R/warnings.R#L44

In the above, the code is comparing `int_new` which is the result of
https://github.com/adibender/pammtools/blob/ab4caeae41748c395772615c70a0cd5e206ebfe6/R/warnings.R#L43

which has extracted the unique event times `tend` in `newdata`. But it's comparing with the output from `int_info(object)`, computed in L41 https://github.com/adibender/pammtools/blob/ab4caeae41748c395772615c70a0cd5e206ebfe6/R/warnings.R#L41

which is a data frame.

Shouldn't line 44 therefore be

```r
if(!all(int_new %in% int_original[["interval"]])) {
```

to compare the `interval` **column** used in the model with the ones supplied in `newdata`?

**Comment by gavinsimpson** [comment]
I see where this happened; it got changed in 1bf8b74

I'll pull a quick PR together.

**Comment by adibender** [comment]
Thanks Gavin, will fix/merge soon. 
I was thinking of removing the warning anyway. Once you estimated the baselinehazard, I don't see a reason to then allow predictions at any time point (or use a finer/different grid compared to the grid used at estimation stage), as we can evaluate the smooth function at any time point.

**Comment by adibender** [comment]
closed in #236
