### ISSUE TITLE
Keep original name of time variable when constructing T mat? 

### ISSUE THREAD

**Issue by adibender** [adibender/pammtools#43]
Currently when using `cumulative`, the constructed time matrix will have the name of the original 
`time` variable in `Surv(time, status)`...

May be misleading, as what's actually constructed is a matrix column with entries t_j

**Comment by adibender** [comment]
@fabian-s keep the current naming scheme and use `toupper` at the end?

**Comment by fabian-s** [comment]
not sure about `toupper` - what about pasting `_mat` or `_vec` to the original name?

**Comment by adibender** [comment]
sounds good, think `_mat` is the way to go
