### ISSUE TITLE
Integration weights not used when constructing covariate matrices

### ISSUE THREAD

**Issue by adibender** [adibender/pammtools#48]
Currently, when constructing matrices for cumulative effects, integration weights are not calculated. Thus estimation will only be correct for exposure time-grids with 1 unit differences between exposure time points

**Comment by adibender** [comment]
@fabian-s What would be the best place to add those? Directly multiply Z matrix with weights matrix at creation?

**Comment by fabian-s** [comment]
To me, those would belong in the `LL`-matrix? These define 0-weights for values $t_z$ outside $\mathcal T(t)$, so they should also represent the quadrature weights for values inside $\mathcal T(t)$...?

**Comment by adibender** [comment]
makes sense. Will have to make some (minor) adjustments to `get_laglead` and similar, which expect 0/1 matrix.
