### ISSUE TITLE
Logo/Hexsticker

### ISSUE THREAD

**Issue by adibender** [adibender/pammtools#70]
@fabian-s Ich habe mitbekommen, dass du jetzt Hexsticker experte bist (tidyfun) :-D 

Ideas?

**Comment by fabian-s** [comment]
was mit pam grier?
![](https://media.giphy.com/media/m2HCD6mBz2f7i/giphy.gif)

**Comment by fabian-s** [comment]
was mit pam anderson?
![](https://media.giphy.com/media/11GvHi88DRLkMo/giphy.gif)

**Comment by adibender** [comment]
nice, kriegt man aber wsl. nur copyright probleme oO
