### ISSUE TITLE
checkmate bug fix breaks unit test

### ISSUE THREAD

**Issue by mllg** [adibender/pammtools#73]
I've recently discovered and fixed a bug w.r.t. missing checks in lists in mllg/checkmate#146. The bugfix now tests lists for elements being identical to NULL which comes closest to a "missing" in lists, but this unfortunately breaks a unit test in your package. Before the fix, the test was defunct and did not trigger any check at all.

Could you please check your assertions accordingly with the devel release of checkmate? I'll prepare a new release of checkmate and want to upload soon.

This is the relevant part of the check log:
```
  ── 1. Failure: Formula special 'func' works as expected (@test-specials.R#6)  ──
  Check on cumu1 isn't true.
  Contains missing values (element 4)
  
  ── 2. Failure: Formula special 'concurrent' works as expected (@test-specials.R#
  Check on ccr1 isn't true.
  Contains missing values (element 3)
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 279 SKIPPED: 0 FAILED: 2
  1. Failure: Formula special 'func' works as expected (@test-specials.R#6) 
  2. Failure: Formula special 'concurrent' works as expected (@test-specials.R#18) 
```

Sorry for the inconvenience.

**Comment by fabian-s** [comment]
@mllg: thx for the great package. Andi will look at the PR shortly, I guess.

**Comment by adibender** [comment]
thx for notification @mllg and thx for fixing @fabian-s 
I've merged the branch. Will fix a couple of other things and resubmit to CRAN in approx. 2 weeks
