### ISSUE TITLE
tutorial paper behind paywall

### ISSUE THREAD

**Issue by fabian-s** [adibender/pammtools#75]
@adibender @hoarzpassey : 
Michel (checkmate-Autor) hat mich drauf aiufmerksam gemacht dass unser tutorial paper was wir auf dem README verlinken hinter ner paywall ist -- was haltet ihr davon den preprint auch noch nach arxiv zu laden und das stattdessen dort zu verlinken...?

**Comment by hoarzpassey** [comment]
Fänd ich super, hab nur grad keine Zeit mich um das Hochladen bei arxiv zu kümmern...@adibender: machst Du das schnell?

**Comment by adibender** [comment]
@fabian-s @hoarzpassey 

Welche version genau dürfen wir bei arxiv hochladen?

**Comment by hoarzpassey** [comment]
Das weiss ich leider auch nicht spontan. Evtl. müsste man da bei Stat Modelling nochmal nachfragen...

**Comment by adibender** [comment]
Alle Beispiele etc. sind natürlich auch in den vignetten auf der Homepage zu finden, aber ist ggf. auch nützlich das Paper öffentlich zu haben...

**Comment by adibender** [comment]
Hier die Antwort von Brian das letzte mal als wir gefragt haben :-) 

> I am attaching p. 5 of the copyright agreement that authors must sign. Briefly:

> 
> * Version 1 (first submitted version) can be placed wherever you want and immediately.
> 
> * Final version (pdf prepared by authors, not by SAGE) can be placed on any non-commercial site 12 months after publication.
>

**Comment by hoarzpassey** [comment]
Sind die zwölf Monate schon rum? Wenn ja, würde ich die finale Version hochladen, falls nicht, dann einfach diese Version 1...

**Comment by adibender** [comment]
12 Monate sind tatsächlich nicht so weit entfernt :scream: 
> First Published February 14, 2018

**Comment by hoarzpassey** [comment]
Dann würde ich fast vorschlagen, wir warten bis zu diesem Termin und laden dann gleich das finale Originalpaper hoch, oder? In der Zwischenzeit kann man es ja zB als private message schon mal bei Research Gate hergeben

**Comment by fabian-s** [comment]
kk, dann wiedervorlage 13.2.!

**Comment by adibender** [comment]
Der Tag der Entscheidung rückt näher! Wie ich die copyright verstehe, soll es 
- die final version von uns sein, nicht die mit dem SAGE layout etc. 
- "placed on any **non-commercial**" site ... also eher nicht researchgate? Also eher arxiv oder technical report bei der LMU?

**Comment by adibender** [comment]
ping @hoarzpassey @fabian-s

**Comment by adibender** [comment]
how about we just upload it into the articles section of the package homepage?

**Comment by hoarzpassey** [comment]
fine for me!

**Comment by fabian-s** [comment]
👍

**Comment by adibender** [comment]
here it is: https://adibender.github.io/pammtools/articles/smj-tutorial.html

**Comment by fabian-s** [comment]
Allerbester Mann! Ich bete für dich dass Du brexit überlebst, wär schade drum.
