### ISSUE TITLE
Model specification

### ISSUE THREAD

**Issue by adibender** [adibender/pammtools#78]
@fabian-s I think its time to think more generally about how we call the functions for data transformation. 

- Right now we use  `Surv(time, status)~ ... + ... | cumulative(...)`, 
although the `Surv(time, status)` part is only a mirrage, as we don't really do anything `Surv` specific with it, except extracting the event time and status variables, while the usual functionality of `Surv()` is not supported, e.g. 

- `Surv(time, status == 2) ~ ...`  (see also #31) or 
- `Surv(time1, time2, status) ~ ... ` e.g. for left truncated data, 
- etc. 

This will also be relevant when/if we extend the functionality to competing risks/multistate models, in which case we need to support calls like 

```r
as_ped(Surv(time, event1) | Surv(time, event2) ~ lin_pred_event1 | lin_pred_event2
```
This could be done nicely using the **`Formula`** functionality, but we already use `|` on the RHS to differentiate between cumulative effects and "normal" effects  `~ ... + ... | cumulative()`. 
The latter may not be necessary, as we can simply extract cumulative via the `specials` function?

**Comment by fabian-s** [comment]
hey, you're on a roll today..... :open_mouth: 

agree, using `specials` and having multiple RHS via `Formula` seems like the way to go, let's try to have as few idiosyncrasies as possible.

need to think more about possible/allowed input data formats as well -- are different event types going to be recorded in different columns (one time column per event type) or in a pair of columns (time, event) with potentially multiple entries per subject? for the first, we'd need multiple RHS, for the second, we could use the event column as "status".

**Comment by adibender** [comment]
We also have to consider different types of censoring/truncation on the LHS

**Comment by adibender** [comment]
I'll close this general issue. Open individual issues for specific cases
